Intento correr en el testeo el siguiente codigo
    from Clases.Cliente import Cliente
    from Clases.Empleado import Empleado
    from Clases.Funciones_extra import *
    from Clases.Reserva import Reserva

    # Testear cosas por acá
    def actualizar_base_reservas(reserva):
        info_reserva = f"{reserva.mail_usuario},{reserva.habitacion.numero},{reserva.check_in},{reserva.check_out}\n"
        with open("D:\Downloads\Estructura de datos y programacion\TP\Tp_Estructura\Bases de datos\db_Reservas copy.csv","a",newline='') as archivo_reservas:
            archivo_reservas.write(info_reserva)

Los errores que van saltando son:
1. Falla la importación en cliente de usuario
Traceback (most recent call last):
  File "d:\Downloads\Prueba tp\Tp_Estructura-1\TESTEOS.py", line 1, in <module>
    from Clases.Cliente import Cliente
  File "d:\Downloads\Prueba tp\Tp_Estructura-1\Clases\Cliente.py", line 1, in <module>
    from Usuario import Usuario
ModuleNotFoundError: No module named 'Usuario'
    !No pareceria estar mal la importacion asi que no se por que no lo toma

2. Al correr Cliente te tira error por importacion circular con Funciones_extra
    !SOLUCIONADO al separar los lectores en otro archivo y no importar clases en Funciones_extra